version: '3'

services:
 db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "15432:5432"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 